### ISSUE TITLE
Auto change sci.fi tag to science.fiction

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#52]
As per tagging rules here: kb.php?id=9, auto replace sci.fi movie tags to science.fiction

**Comment by mueslo** [comment]
got an example that gets tagged as sci.fi?

**Comment by eeeeeeeeeve** [comment]
Yup!

CQ.2001.720p.WEB-DL.AAC2.0.H.264-CtrlHD.mkv

**Comment by mueslo** [comment]
Probably not gonna change this any time soon though, see also forums.php?action=viewthread&threadid=3365&page=1#post50593 

I personally also prefer sci.fi for movies/tv over science.fiction and the rules don't actually state that sci.fi is not an allowed tag. For movies sci.fi is actually a more popular tag (not sure how much of that is due to pythonbits though).
